### ISSUE TITLE
Implement voting

### ISSUE THREAD

**Issue by LonnyGomes** [72Fest/ng2-72-film-fest#13]
**Summary**

Add voting/liking support

Relates to #5 

**Tasks**
- [x] configure user preferences to store vote status
- [x] update vote models to manage status
- [x] create dataManager calls
